#!/bin/sh
# Generates a throwaway self-signed certificate when none has been mounted.
#
# Production bind-mounts the real Cloudflare Origin CA pair over /etc/nginx/certs, so this does
# nothing there. It exists so that `docker compose up --build` on a laptop -- where no certificate
# exists and none should -- still starts, instead of nginx aborting on a missing ssl_certificate.
#
# The generated pair is deliberately worthless: self-signed, CN=localhost, regenerated on every
# start. Nothing should ever trust it, and Cloudflare's Full (strict) mode explicitly will not.
set -e

CERT_DIR=/etc/nginx/certs
CERT="$CERT_DIR/origin.pem"
KEY="$CERT_DIR/origin.key"

# /etc/nginx/certs is a bind mount, so a placeholder generated by an earlier start is still sitting
# there on the next one. Reporting "using mounted certificate" for it would be actively misleading:
# that is the exact message someone reads to confirm the real certificate took effect. Tell the two
# apart by issuer -- a Cloudflare Origin CA cert is issued by Cloudflare, the placeholder issues
# itself -- rather than by a marker file, which goes stale the moment the real pair is dropped in.
if [ -f "$CERT" ] && [ -f "$KEY" ]; then
    issuer=$(openssl x509 -in "$CERT" -noout -issuer 2>/dev/null || echo 'unreadable')
    subject=$(openssl x509 -in "$CERT" -noout -subject 2>/dev/null || echo 'unreadable')
    if [ "$issuer" = "unreadable" ]; then
        echo "[tls] ERROR: $CERT exists but could not be parsed as a certificate"
    elif [ "${issuer#issuer=}" = "${subject#subject=}" ]; then
        echo "[tls] WARNING: certificate is self-signed ($subject)."
        echo "[tls] WARNING: this is the local placeholder. Cloudflare Full (strict) will fail against it."
    else
        echo "[tls] using mounted certificate ($issuer)"
    fi
    exit 0
fi

echo "[tls] no certificate mounted -- generating a self-signed placeholder (NOT for production)"
mkdir -p "$CERT_DIR"
openssl req -x509 -nodes -newkey rsa:2048 -days 365     -keyout "$KEY" -out "$CERT" -subj "/CN=localhost" >/dev/null 2>&1
